create database dailyneed;
use dailyneed ;

create table ORDERS(
 ORDER_ID INT NOT NULL,
 CUSTOMER_NAME VARCHAR(20) NOT NULL ,
 ORDER_DATE INT NOT NULL,
 ADDRESS CHAR(30),
 UNIQUE(ORDER_ID)
 );
 CREATE TABLE CUSTOMERS(
   CUSTOMERS_ID   INT              NOT NULL,
   CUSTOMER_NAME VARCHAR (20)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  CHAR (30) ,
   SALARY   DECIMAL (18, 2),       
   PRIMARY KEY (CUSTOMERS_ID)
);
INSERT INTO ORDERS VALUES (11,'AMAN',01/2/2019,'DELHI');
INSERT INTO ORDERS VALUES (12,'RAMAN',25/5/2019,'GOA');
INSERT INTO ORDERS VALUES (13,'SUMAN',31/3/2019,'DUBAI');
INSERT INTO ORDERS VALUES (14,'TARUN',30/4/2019,'DENMARK');
INSERT INTO ORDERS VALUES (15,'ARUN',15/6/2019,'SEATTE');
INSERT INTO ORDERS VALUES (16,'VARUN',26/7/2019,'PALAM');
INSERT INTO ORDERS VALUES (18,'NITIN',11/9/2019,'DELHI');
INSERT INTO ORDERS VALUES (19,'ANKIT',27/11/2019,'MASOORI');
INSERT INTO ORDERS VALUES (20,'ADDI',28/12/2019,'PANJIM');
INSERT INTO ORDERS VALUES (21,'AKKI',21/2/2019,'PALOLEM');
INSERT INTO ORDERS VALUES (22,'KIKI',16/1/2019,'COVAL');
INSERT INTO ORDERS VALUES (23,'MANISH',24/2/2019,'MOBAR');
INSERT INTO ORDERS VALUES (24,'MANSHI',17/2/2019,'AGONDA');
INSERT INTO ORDERS VALUES (25,'DIPU',02/2/2019,'BAGA');
INSERT INTO ORDERS VALUES (26,'DEEPAK',14/2/2019,'ARAMBOL');
INSERT INTO ORDERS VALUES (27,'VINEET',13/2/2019,'POLLEM');
INSERT INTO ORDERS VALUES (28,'VINITA',01/2/2019,'KARVAR');
INSERT INTO ORDERS VALUES (29,'VARSHA',07/2/2018,'PATNEM');
INSERT INTO ORDERS VALUES (30,'VASU',10/2/2019,'RAJBAG');
INSERT INTO ORDERS VALUES (31,'VINOD',08/8/2019,'MASUPA');
INSERT INTO ORDERS VALUES (32,'VAIBHAV',22/2/2019,'GOLGODIA');


INSERT INTO CUSTOMERS VALUES (11,'AMAN',45,'DELHI',10000);
INSERT INTO CUSTOMERS VALUES (12,'RAMAN',65,'GOA',20000);
INSERT INTO CUSTOMERS VALUES (13,'SUMAN',75,'DUBAI',25000);
INSERT INTO CUSTOMERS VALUES (14,'TARUN',25,'DENMARK',30000);
INSERT INTO CUSTOMERS VALUES (15,'ARUN',33,'SEATTE',28000);
INSERT INTO CUSTOMERS VALUES (16,'VARUN',22,'PALAM',21000);
INSERT INTO CUSTOMERS VALUES (18,'NITIN',16,'DELHI',22000);
INSERT INTO CUSTOMERS VALUES (19,'ANKIT',34,'MASOORI',23000);
INSERT INTO CUSTOMERS VALUES (20,'ADDI',30,'PANJIM',24000);
INSERT INTO CUSTOMERS VALUES (21,'AKKI',35,'PALOLEM',26000);
INSERT INTO CUSTOMERS VALUES (22,'KIKI',26,'COVAL',27000);
INSERT INTO CUSTOMERS VALUES (23,'MANISH',29,'MOBAR',29000);
INSERT INTO CUSTOMERS VALUES (24,'MANSHI',31,'AGONDA',31000);
INSERT INTO CUSTOMERS VALUES (25,'DIPU',39,'BAGA',32000);
INSERT INTO CUSTOMERS VALUES (26,'DEEPAK',63,'ARAMBOL',33000);
INSERT INTO CUSTOMERS VALUES (27,'VINEET',53,'POLLEM',34000);
INSERT INTO CUSTOMERS VALUES (28,'VINITA',52,'KARVAR',35000);
INSERT INTO CUSTOMERS VALUES (29,'VARSHA',50,'PATNEM',36000);
INSERT INTO CUSTOMERS VALUES (30,'VASU',47,'RAJBAG',37000);
INSERT INTO CUSTOMERS VALUES (31,'VINOD',46,'MASUPA',38000);
INSERT INTO CUSTOMERS VALUES (32,'VAIBHAV',44,'GOLGODIA',39000);

SELECT * FROM ORDERS
SELECT * FROM CUSTOMERS
SELECT ORDER_ID,CUSTOMER_NAME, ADDRESS FROM ORDERS;
SELECT CUSTOMERS_ID, CUSTOMER_NAME, SALARY 
FROM CUSTOMERS
WHERE SALARY > 25000;

SELECT CUSTOMERS_ID, CUSTOMER_NAME, SALARY 
FROM CUSTOMERS
WHERE CUSTOMER_NAME = 'ADDI';

SELECT CUSTOMERS_ID, CUSTOMER_NAME, SALARY
FROM CUSTOMERS
WHERE SALARY>35000 AND AGE>40;
 
SELECT CUSTOMERS_ID, CUSTOMER_NAME, SALARY
FROM CUSTOMERS
WHERE SALARY>35000 OR AGE>50;

 UPDATE CUSTOMERS
 SET CUSTOMER_NAME= 'RAMAN'
 WHERE CUSTOMERS_ID=32;
 
 
 SELECT * FROM CUSTOMERS
WHERE SALARY LIKE '3%';

SELECT distinct SALARY FROM CUSTOMERS;

SELECT COUNT(distinct SALARY) FROM CUSTOMERS;

DELETE CUSTOMER_NAME FROM CUSTOMERS
WHERE CUSTOMER_NAME= 'AMAN';


SELECT *FROM CUSTOMERS
WHERE SALARY=30000 AND(ADDRESS='DENMARK' OR ADDRESS='POLLEM');

SELECT *FROM CUSTOMERS
WHERE NOT ADDRESS='POLLEM';

SELECT *FROM CUSTOMERS
 ORDER BY ADDRESS DESC ;
 
 SELECT *FROM CUSTOMERS
 ORDER BY CUSTOMER_NAME ;
 
 SELECT *FROM CUSTOMERS
 ORDER BY ADDRESS  DESC, CUSTOMER_NAME ASC;
 
 SELECT ADDRESS FROM CUSTOMERS
 WHERE ADDRESS IS  NOT NULL;
 
 UPDATE CUSTOMERS
 SET CUSTOMER_NAME='AKKI'
 where CUSTOMERS_ID=31;
 
 
 UPDATE CUSTOMERS
 SET CUSTOMER_NAME='SANEER'
 where ADDRESS='DELHI';

SELECT *
FROM CUSTOMERS
LIMIT 3;


SELECT ADDRESS
FROM CUSTOMERS
WHERE SALARY>30000 
LIMIT 3;

SELECT ADDRESS
FROM CUSTOMERS
WHERE SALARY>30000 AND AGE>50
LIMIT 3;

SELECT ORDER_ID,ORDER_DATE,AGE ,SALARY
FROM ORDERS
LEFT JOIN CUSTOMERS
ON ORDERS.ORDER_ID=CUSTOMERS.CUSTOMERS_ID
UNION
SELECT ORDER_ID,ORDER_DATE,AGE ,SALARY
FROM ORDERS
RIGHT JOIN CUSTOMERS
ON ORDERS.ORDER_ID=CUSTOMERS.CUSTOMERS_ID;

SELECT ORDER_ID FROM ORDERS
UNION
SELECT AGE FROM CUSTOMERS


SELECT SALARY 
FROM CUSTOMERS
WHERE SALARY <35000;


SELECT SALARY 
FROM CUSTOMERS
WHERE SALARY BETWEEN 35000 AND 50000;


SELECT COUNT(SALARY) 
FROM CUSTOMERS
WHERE SALARY BETWEEN 35000 AND 50000;


SELECT MAX(SALARY )
FROM CUSTOMERS;

SELECT MIN(SALARY )
FROM CUSTOMERS;

SELECT MIN(SALARY )
FROM CUSTOMERS
WHERE AGE >50;

SELECT AVG(SALARY )
FROM CUSTOMERS;

SELECT SUM(SALARY )
FROM CUSTOMERS;

SELECT ADDRESS AS DETAILS
FROM CUSTOMERS;

SELECT ADDRESS
FROM CUSTOMERS
WHERE ADDRESS IN ('DELHI','GOA','POLLEM');

SELECT ADDRESS
FROM CUSTOMERS
group by ADDRESS ;

SELECT SALARY
FROM CUSTOMERS
group by SALARY having SALARY >35000 ;

create view qaz AS
SELECT SALARY
FROM CUSTOMERS
group by SALARY having SALARY >35000 ;


/* ==============================================*/
use dailyneed;

select * from customers;


select max(salary) from customers;



select min(salary) from customers;


select avg(salary) from customers;


-- 
select *, length(customer_name), lower(customer_name) , replace(customer_name,'A','xy') from customers;

 
  --  create replica of existing table 


select * from customers;


create table customer(cid int, cname varchar(100), age int, address varchar(300));

insert into customer_copy (cid,cname,age,address)
select customers_id,customer_name,age,address from customers;


select * from customer_copy;

update customer_copy
set age =34
where cid=11;
 

-- union 
select cid,cname,age,address from customer_copy
union 
select customers_id, customer_name, age, address from customers;
 
 
 
-- union all 
select cid,cname,age,address from customer_copy
union all 
select customers_id, customer_name, age, address from customers;
 
 
 
 
--- 

select * from customers 
select * from orders 

 --  inner join 
 
 select * 
 from customers as c inner join orders as s
	on c.customers_id  = s.order_id;
    
    
 select c.customers_id,c.customer_name, c.salary,s.order_date   
 from customers as c inner join orders as s
	on c.customers_id  = s.order_id;
    
    
     
 select c.customers_id,c.customer_name, c.salary,s.order_date   
 from customers as c left join orders as s
	on c.customers_id  = s.order_id;
    
    
 select c.customers_id,c.customer_name, c.salary,s.order_date  
 from customers as c right join orders as s
	on c.customers_id  = s.order_id;
    
    
    
    
    select fname ,  beneficiary name , pump id ,rms_id 
    from  beneficiary table inner join pump table 
    on beneficiary table.contact_no= pump table
    